package app.enums;

/**
 * Created by Yixiu Liu on 11/29/2018.
 */
public enum Property {

    STAGNANT_ITERATION, MAX_RUNTIME,MIN_TOUCHING,
    ALGO_NAME_ANNEAL,
    ALGO_NAME_GROW,
    ANNEALINGTHRESHOLD,
    GETSTATE_NAME,
    GETDISTRICT_STATEID,
    GETPRECINCT_DISTRICTID,
    GETPOPULATION_DISTRICTID ,
    LOADELECTIONDATA_DISTRICTID ,
    GETDEMOGRAPHICS_PRECINCTID,
    GETELECTIONDATA_PRECINCTID,
    GETSTATECONSTITUTION_NAME,

}
